version: 1
services:
  - type: web
    name: safotime-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromParam: PORT
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
